### ISSUE TITLE
SGP40

### ISSUE THREAD

**Issue by JWynen** [adafruit/WipperSnapper_Component_Requests#5]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
Adafruit SGP40 Air Quality Sensor 

**Product URL or Datasheet**
adafru.it/4829

**Additional context**
Add any other context about the component request here.

**Comment by brentru** [comment]
Migrating request over to https://github.com/adafruit/Wippersnapper_Components/issues/27
